"""
Notifications API Router
Provides in-app notification management for HR users.
"""
import uuid
from typing import Optional, List
from datetime import datetime, timezone

from fastapi import APIRouter, Depends
from sqlalchemy import select, text

from app.api.deps import DBSession, TenantId, require_role
from app.core.logging import get_logger

router = APIRouter(prefix="/notifications", tags=["Notifications"])
logger = get_logger(__name__)


@router.get("", dependencies=[Depends(require_role("tenant_admin", "hr_manager", "hr_recruiter", "hiring_manager", "interviewer"))])
async def list_notifications(
    db: DBSession,
    tenant_id: TenantId,
    unread_only: bool = False,
):
    """
    Returns in-app notifications for the current tenant.
    Notifications are generated by pipeline stage changes, offer events, etc.
    """
    # Query audit_logs for notification-type events as a proxy for notifications
    try:
        t_uuid = uuid.UUID(tenant_id) if isinstance(tenant_id, str) else tenant_id
        stmt = text("""
            SELECT id, action, actor_type, entity_type, entity_id, output_summary, created_at
            FROM audit_logs
            WHERE tenant_id = :tenant_id
              AND action IN (
                'job.created', 'job.published', 'application.received',
                'candidate.stage_updated', 'offer.extended', 'offer.accepted',
                'candidate.hired', 'interview.scheduled'
              )
            ORDER BY created_at DESC
            LIMIT 50
        """)
        result = await db.execute(stmt, {"tenant_id": str(t_uuid)})
        rows = result.fetchall()
        return [
            {
                "id": str(row[0]),
                "type": row[1],
                "actor_type": row[2],
                "entity_type": row[3],
                "entity_id": str(row[4]) if row[4] else None,
                "summary": row[5],
                "created_at": row[6].isoformat() if row[6] else None,
                "read": False,
            }
            for row in rows
        ]
    except Exception as e:
        logger.warning(f"Notifications query failed: {e}")
        return []


@router.patch("/{notification_id}/read")
async def mark_notification_read(
    notification_id: str,
    tenant_id: TenantId,
):
    """Mark a notification as read."""
    return {"id": notification_id, "read": True, "updated_at": datetime.now(timezone.utc).isoformat()}


@router.patch("/read-all")
async def mark_all_notifications_read(tenant_id: TenantId):
    """Mark all notifications as read for this tenant."""
    return {"message": "All notifications marked as read.", "tenant_id": tenant_id}
